//FETCH
export const FETCH_ATTENDANCES_REQUEST = 'FETCH_ATTENDANCES_REQUEST';
export const FETCH_ATTENDANCES_SUCCESS = 'FETCH_ATTENDANCES_SUCCESS';
export const FETCH_ATTENDANCES_FAILURE = 'FETCH_ATTENDANCES_FAILURE';

//ADD USER
export const ADD_ATTENDANCE_REQUEST = 'ADD_ATTENDANCE_REQUEST';
export const ADD_ATTENDANCE_SUCCESS = 'ADD_ATTENDANCE_SUCCESS';
export const ADD_ATTENDANCE_FAILURE = 'ADD_ATTENDANCE_FAILURE';

//UPDATE EMPLOYEE
export const UPDATE_ATTENDANCE_REQUEST = 'UPDATE_ATTENDANCE_REQUEST';
export const UPDATE_ATTENDANCE_SUCCESS = 'UPDATE_ATTENDANCE_SUCCESS';
export const UPDATE_ATTENDANCE_FAILURE = 'UPDATE_ATTENDANCE_FAILURE';

//DELETE EMPLOYEEapi
export const DELETE_ATTENDANCE_REQUEST = 'DELETE_ATTENDANCE_REQUEST';
export const DELETE_ATTENDANCE_SUCCESS = 'DELETE_ATTENDANCE_SUCCESS';
export const DELETE_ATTENDANCE_FAILURE = 'DELETE_ATTENDANCE_FAILURE';

//QRCODE 
export const QRCODE_ATTENDANCE_REQUEST = 'QRCODE_ATTENDANCE_REQUEST';
export const QRCODE_ATTENDANCE_SUCCESS = 'QRCODE_ATTENDANCE_SUCCESS';
export const QRCODE_ATTENDANCE_FAILURE = 'QRCODE_ATTENDANCE_FAILURE';


