//FETCH DEDUCTIONS
export const FETCH_DEDUCTIONS_REQUEST = 'FETCH_DEDUCTIONS_REQUEST';
export const FETCH_DEDUCTIONS_SUCCESS = 'FETCH_DEDUCTIONS_SUCCESS';
export const FETCH_DEDUCTIONS_FAILURE = 'FETCH_DEDUCTIONS_FAILURE';

//ADD DEDUCTION
export const ADD_DEDUCTION_REQUEST = 'ADD_DEDUCTION_REQUEST';
export const ADD_DEDUCTION_SUCCESS = 'ADD_DEDUCTION_SUCCESS';
export const ADD_DEDUCTION_FAILURE = 'ADD_DEDUCTION_FAILURE';

//UPDATE DEDUCTION
export const UPDATE_DEDUCTION_REQUEST = 'UPDATE_DEDUCTION_REQUEST';
export const UPDATE_DEDUCTION_SUCCESS = 'UPDATE_DEDUCTION_SUCCESS';
export const UPDATE_DEDUCTION_FAILURE = 'UPDATE_DEDUCTION_FAILURE';

//DELETE DEDUCTION
export const DELETE_DEDUCTION_REQUEST = 'DELETE_DEDUCTION_REQUEST';
export const DELETE_DEDUCTION_SUCCESS = 'DELETE_DEDUCTION_SUCCESS';
export const DELETE_DEDUCTION_FAILURE = 'DELETE_DEDUCTION_FAILURE';




