//FETCH ALL DEPARTMENT
export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';

//ADD/CREATE DEPARTMENT
export const ADD_DEPARTMENT_REQUEST = 'ADD_DEPARTMENT_REQUEST';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAILURE = 'ADD_DEPARTMENT_FAILURE';

//UPDATE DEPARTMENT
export const UPDATE_DEPARTMENT_REQUEST = 'UPDATE_DEPARTMENT_REQUEST';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';

//DELETE DEPARTMENT
export const DELETE_DEPARTMENT_REQUEST = 'DELETE_DEPARTMENT_REQUEST';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';

//DEACTIVATE DEPARTMENT
export const DEACTIVATE_DEPARTMENT_REQUEST = 'DEACTIVATE_DEPARTMENT_REQUEST';
export const DEACTIVATE_DEPARTMENT_SUCCESS = 'DEACTIVATE_DEPARTMENT_SUCCESS';
export const DEACTIVATE_DEPARTMENT_FAILURE = 'DEACTIVATE_DEPARTMENT_FAILURE';


