//FETCH
export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';

//ADD USER
export const ADD_DEPARTMENT_REQUEST = 'ADD_DEPARTMENT_REQUEST';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAILURE = 'ADD_DEPARTMENT_FAILURE';

//UPDATE DEPARTMENT
export const UPDATE_DEPARTMENT_REQUEST = 'UPDATE_DEPARTMENT_REQUEST';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';

//DELETE DEPARTMENT
export const DELETE_DEPARTMENT_REQUEST = 'DELETE_DEPARTMENT_REQUEST';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';

//UPLOAD AND  UPDATE IMAGE DEPARTMENT
export const UPLOAD_AND_UPDATE_DEPARTMENT_REQUEST = 'UPLOAD_AND_UPDATE_DEPARTMENT_REQUEST';
export const UPLOAD_AND_UPDATE_DEPARTMENT_SUCCESS = 'UPLOAD_AND_UPDATE_DEPARTMENT_SUCCESS';
export const UPLOAD_AND_UPDATE_DEPARTMENT_FAILURE = 'UPLOAD_AND_UPDATE_DEPARTMENT_FAILURE';



