//FETCH
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

//ADD USER
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

//UPDATE EMPLOYEE
export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE';

//DELETE EMPLOYEE
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';

//UPLOAD AND  UPDATE IMAGE EMPLOYEE
export const UPLOAD_AND_UPDATE_EMPLOYEE_REQUEST = 'UPLOAD_AND_UPDATE_EMPLOYEE_REQUEST';
export const UPLOAD_AND_UPDATE_EMPLOYEE_SUCCESS = 'UPLOAD_AND_UPDATE_EMPLOYEE_SUCCESS';
export const UPLOAD_AND_UPDATE_EMPLOYEE_FAILURE = 'UPLOAD_AND_UPDATE_EMPLOYEE_FAILURE';

//REGISTER EMPLOYEE 
export const REGISTER_EMPLOYEE_REQUEST = 'REGISTER_EMPLOYEE_REQUEST';
export const REGISTER_EMPLOYEE_SUCCESS = 'REGISTER_EMPLOYEE_SUCCESS';
export const REGISTER_EMPLOYEE_FAILURE = 'REGISTER_EMPLOYEE_FAILURE';


//LOGIN EMPLOYEE
export const LOGIN_EMPLOYEE_REQUEST = 'LOGIN_EMPLOYEE_REQUEST';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_EMPLOYEE_FAILURE = 'LOGIN_EMPLOYEE_FAILURE';


