//FETCH DEDUCTIONS
export const FETCH_OVERTIMES_REQUEST = 'FETCH_OVERTIMES_REQUEST';
export const FETCH_OVERTIMES_SUCCESS = 'FETCH_OVERTIMES_SUCCESS';
export const FETCH_OVERTIMES_FAILURE = 'FETCH_OVERTIMES_FAILURE';

//ADD DEDUCTION
export const ADD_OVERTIME_REQUEST = 'ADD_OVERTIME_REQUEST';
export const ADD_OVERTIME_SUCCESS = 'ADD_OVERTIME_SUCCESS';
export const ADD_OVERTIME_FAILURE = 'ADD_OVERTIME_FAILURE';

//UPDATE OVERTIME
export const UPDATE_OVERTIME_REQUEST = 'UPDATE_OVERTIME_REQUEST';
export const UPDATE_OVERTIME_SUCCESS = 'UPDATE_OVERTIME_SUCCESS';
export const UPDATE_OVERTIME_FAILURE = 'UPDATE_OVERTIME_FAILURE';

//DELETE-DEACTIVATE OVERTIME
export const DELETE_OVERTIME_REQUEST = 'DELETE_OVERTIME_REQUEST';
export const DELETE_OVERTIME_SUCCESS = 'DELETE_OVERTIME_SUCCESS';
export const DELETE_OVERTIME_FAILURE = 'DELETE_OVERTIME_FAILURE';

//SEARCH OVERTIME
export const SEARCH_OVERTIME_REQUEST = 'SEARCH_OVERTIME_REQUEST';
export const SEARCH_OVERTIME_SUCCESS = 'SEARCH_OVERTIME_SUCCESS';
export const SEARCH_OVERTIME_FAILURE = 'SEARCH_OVERTIME_FAILURE';




