//FETCH PAYROLLS
export const FETCH_PAYROLLS_REQUEST = 'FETCH_PAYROLLS_REQUEST';
export const FETCH_PAYROLLS_SUCCESS = 'FETCH_PAYROLLS_SUCCESS';
export const FETCH_PAYROLLS_FAILURE = 'FETCH_PAYROLLS_FAILURE';

//ADD DEDUCTION
export const ADD_PAYROLL_REQUEST = 'ADD_PAYROLL_REQUEST';
export const ADD_PAYROLL_SUCCESS = 'ADD_PAYROLL_SUCCESS';
export const ADD_PAYROLL_FAILURE = 'ADD_PAYROLL_FAILURE';

//UPDATE PAYROLL
export const UPDATE_PAYROLL_REQUEST = 'UPDATE_PAYROLL_REQUEST';
export const UPDATE_PAYROLL_SUCCESS = 'UPDATE_PAYROLL_SUCCESS';
export const UPDATE_PAYROLL_FAILURE = 'UPDATE_PAYROLL_FAILURE';

//DELETE PAYROLL
export const DELETE_PAYROLL_REQUEST = 'DELETE_PAYROLL_REQUEST';
export const DELETE_PAYROLL_SUCCESS = 'DELETE_PAYROLL_SUCCESS';
export const DELETE_PAYROLL_FAILURE = 'DELETE_PAYROLL_FAILURE';




