//FETCH RATES
export const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE';

//ADD RATE
export const ADD_RATE_REQUEST = 'ADD_RATE_REQUEST';
export const ADD_RATE_SUCCESS = 'ADD_RATE_SUCCESS';
export const ADD_RATE_FAILURE = 'ADD_RATE_FAILURE';

//UPDATE RATE
export const UPDATE_RATE_REQUEST = 'UPDATE_RATE_REQUEST';
export const UPDATE_RATE_SUCCESS = 'UPDATE_RATE_SUCCESS';
export const UPDATE_RATE_FAILURE = 'UPDATE_RATE_FAILURE';

//DELETE RATE
export const DELETE_RATE_REQUEST = 'DELETE_RATE_REQUEST';
export const DELETE_RATE_SUCCESS = 'DELETE_RATE_SUCCESS';
export const DELETE_RATE_FAILURE = 'DELETE_RATE_FAILURE';




